global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "deakin-coffee-app"
    static_configs:
      - targets: ["coffee-prod:3001", "coffee-staging:3001"]
    metrics_path: "/metrics"
